baseURL = "https://gioeleali.github.io/"
title = "Gioele Alì"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[minify]
disableXML = true

[languages.en]
languageAltTitle = "Italiano"
weight = 1
title = "Gioele Alì"

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

  [languages.en.profileMode]
  enabled = true
  title = "Gioele Alì"
  imageUrl = "https://media-exp1.licdn.com/dms/image/C4E03AQFs4w21m0N-JA/profile-displayphoto-shrink_800_800/0/1598707861253?e=1670457600&v=beta&t=nGT7wsxMoQLSmjAsQzXql8KknjcDelv8nQl5TUHqbJw"
  imageTitle = "ProfileMode image"
  subtitle = "Semplicemente io, incuriosito da questo affascinante e strano mondo della programmazione."

    [[languages.en.profileMode.buttons]]
    name = "Curriculum Vitae"
    url = "about"

#[[languages.en.menu.main]]
#name = "Indice"
#url = "archives"
#weight = 5

[[languages.en.menu.main]]
name = "Cerca"
url = "search/"
weight = 11

#[[languages.en.menu.main]]
#name = "Tag"
#url = "tags/"
#weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
favicon_ico = "favicon.ico"
favicon_ico_sizes = "16x16 32x32"
appleicon = "apple-touch-icon"


[[params.socialIcons]]
name = "telegram"
url = "https://t.me/gioeleali"

[[params.socialIcons]]
name = "reddit"
url = "https://reddit.com/u/gioeleali"

[[params.socialIcons]]
name = "discord"
url = "https://discord.gg/JK7BWpUE"

[params.assets]
disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
