baseURL = "https://gioeleali.github.io/"
title = "Gioele Alì"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[minify]
disableXML = true

[languages.en]
languageAltTitle = "Italiano"
weight = 1
title = "Gioele Alì"

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

  [languages.en.profileMode]
  enabled = true
  title = "Gioele Alì"
  imageUrl = "/me.jpg"
  imageTitle = "Immagine del Profilo Gioele Alì"
  subtitle = "Anno 2001, appassionato di tecnologia e motori, incuriosito da questo affascinante e strano mondo della programmazione.💡"

    [[languages.en.profileMode.buttons]]
    name = "Curriculum Vitae"
    url = "curriculum-vitae"

    [[languages.en.profileMode.buttons]]
    name = "Chi sono"
    url = "about"

#[[languages.en.menu.main]]
#name = "Indice"
#url = "archives"
#weight = 5

[[languages.en.menu.main]]
name = "Archivio"
url = "archive"
weight = 10

[[languages.en.menu.main]]
name = "Cerca"
url = "search/"
weight = 11

#[[languages.en.menu.main]]
#name = "Tag"
#url = "tags/"
#weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
favicon_ico = "favicon.ico"
favicon_ico_sizes = "16x16 32x32"
appleicon = "apple-touch-icon"

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/gioeleali"

[[params.socialIcons]]
name = "github"
url = "https://github.com/gioeleali"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/gioeleali"

[params.assets]
disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
