baseURL = "https://gioeleali.github.io/"
title = "Gioele Alì"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[minify]
disable = ["XML"]

[languages]
  [languages.it]
    languageName = "Italiano"
    weight = 1
    title = "Gioele Alì"

    [languages.it.taxonomies]
      category = "categories"
      tag = "tags"
      series = "series"

    [languages.it.params.profileMode]
      enabled = true
      title = "Gioele Alì"
      imageUrl = "/me.jpg"
      imageTitle = "Immagine del Profilo Gioele Alì"
      subtitle = "Anno 2001, appassionato di tecnologia e motori, incuriosito da questo affascinante e strano mondo della programmazione.💡"

      [[languages.it.params.profileMode.buttons]]
        name = "Curriculum Vitae"
        url = "curriculum-vitae-it"

  [languages.en]
    languageName = "English"
    weight = 2
    title = "Gioele Alì"

    [languages.en.taxonomies]
      category = "categories"
      tag = "tags"
      series = "series"

    [languages.en.params.profileMode]
      enabled = true
      title = "Gioele Alì"
      imageUrl = "/me.jpg"
      imageTitle = "Profile Picture Gioele Ali"
      subtitle = "Year 2001, passionate about technology and engines, intrigued by this fascinating and strange world of programming.💡"

      [[languages.en.params.profileMode.buttons]]
        name = "Curriculum Vitae"
        url = "curriculum-vitae-en"

#[menu]
#  [[menu.main]]
#    name = "Indice"
#    url = "archives"
#    weight = 5

#  [[menu.main]]
#    name = "Archivio"
#    url = "archive"
#    weight = 10

#  [[menu.main]]
#    name = "Cerca"
#    url = "search/"
#    weight = 11

#  [[menu.main]]
#    name = "Tag"
#    url = "tags/"
#    weight = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  favicon_ico = "favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  appleicon = "apple-touch-icon"
  copyright = "© 2022 - 2023 [Gioele Alì](https://gioeleali.github.io) |"

  [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/gioeleali"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/gioeleali"

  #[[params.socialIcons]]
  #name = "instagram"
  #url = "https://instagram.com/gioeleali"

[params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[privacy.vimeo]
  disabled = false
  simple = true

[privacy.twitter]
  disabled = false
  enableDNT = true
  simple = true

[privacy.instagram]
  disabled = false
  simple = true

[privacy.youtube]
  disabled = false
  privacyEnhanced = true

[services.instagram]
  disableInlineCSS = true

[services.twitter]
  disableInlineCSS = true
